# Generated by Django 4.2.1 on 2023-05-23 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_buyer_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='user_type',
            new_name='utype',
        ),
    ]
