# Generated by Django 4.2.1 on 2023-05-23 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_user_type_customuser_utype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='utype',
            new_name='user_type',
        ),
    ]
