# Generated by Django 4.2.1 on 2023-05-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_bill_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='payment_status',
            field=models.BooleanField(choices=[(False, 'FULFILLED'), (True, 'UNFULFILLED')]),
        ),
    ]
