# Generated by Django 4.2.1 on 2023-05-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_bill_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='payment_status',
            field=models.BooleanField(choices=[('filfilled', 'FULFILLED'), ('unfulfilled', 'UNFULFILLED')]),
        ),
    ]
