# Generated by Django 4.2.1 on 2023-05-31 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_bill_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('seller', 'Seller'), ('buyer', 'Buyer')], max_length=10),
        ),
    ]
